version: '3'

services:
  node:
    restart: "no"
    image: piplsearch/games-node:development
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /games
    command: bash -c "npm install && npm run start"
    volumes:
      - .:/games
    ports:
      - "3010:3010"

networks:
  apps_network:
    external: true
